# Mapping of country names to ISO 3166-1 alpha-2 country codes
COUNTRY_TO_CODE = {
    # Africa
    'algeria': 'dz',
    'angola': 'ao',
    'benin': 'bj',
    'botswana': 'bw',
    'burkina faso': 'bf',
    'burundi': 'bi',
    'cameroon': 'cm',
    'cabo verde': 'cv',
    'central african republic': 'cf',
    'chad': 'td',
    'comoros': 'km',
    'congo': 'cg',
    "cote d'ivoire": 'ci',
    'democratic republic of the congo': 'cd',
    'djibouti': 'dj',
    'egypt': 'eg',
    'equatorial guinea': 'gq',
    'eritrea': 'er',
    'eswatini': 'sz',
    'ethiopia': 'et',
    'gabon': 'ga',
    'gambia': 'gm',
    'ghana': 'gh',
    'guinea': 'gn',
    'guinea-bissau': 'gw',
    'kenya': 'ke',
    'lesotho': 'ls',
    'liberia': 'lr',
    'libya': 'ly',
    'madagascar': 'mg',
    'malawi': 'mw',
    'mali': 'ml',
    'mauritania': 'mr',
    'mauritius': 'mu',
    'morocco': 'ma',
    'mozambique': 'mz',
    'namibia': 'na',
    'niger': 'ne',
    'nigeria': 'ng',
    'rwanda': 'rw',
    'sao tome and principe': 'st',
    'senegal': 'sn',
    'seychelles': 'sc',
    'sierra leone': 'sl',
    'somalia': 'so',
    'south africa': 'za',
    'south sudan': 'ss',
    'sudan': 'sd',
    'tanzania': 'tz',
    'togo': 'tg',
    'tunisia': 'tn',
    'uganda': 'ug',
    'zambia': 'zm',
    'zimbabwe': 'zw',
    
    # Common non-African countries
    'brazil': 'br',
    'france': 'fr',
    'germany': 'de',
    'italy': 'it',
    'netherlands': 'nl',
    'portugal': 'pt',
    'spain': 'es',
    'united kingdom': 'gb',
    'united states': 'us',
    'argentina': 'ar',
    'belgium': 'be',
    'croatia': 'hr',
    'denmark': 'dk',
    'england': 'gb-eng',
    'finland': 'fi',
    'greece': 'gr',
    'ireland': 'ie',
    'japan': 'jp',
    'south korea': 'kr',
    'mexico': 'mx',
    'norway': 'no',
    'poland': 'pl',
    'russia': 'ru',
    'sweden': 'se',
    'switzerland': 'ch',
    'turkey': 'tr',
    'ukraine': 'ua',
    'united arab emirates': 'ae',
    'uruguay': 'uy',
    'venezuela': 've'
}

def get_country_code(country_name):
    """
    Get the ISO 3166-1 alpha-2 country code for a given country name.
    Returns 'zm' (Zambia) if the country is not found.
    """
    if not country_name:
        return 'zm'
    return COUNTRY_TO_CODE.get(country_name.lower().strip(), 'zm')
